apiVersion: v1
kind: PersistentVolume
metadata:
  name: devlaba-pv
  namespace: jenkins1
spec:
  storageClassName: devlaba_storage_class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
