apiVersion: v1
kind: Service
metadata:
  name: devlaba-db-service
  namespace: jenkins1
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: devlaba-db
