apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devlaba-db
  namespace: jenkins1
spec:
  serviceName: "devlaba-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: devlaba-db
  template:
    metadata:
      labels:
        app: devlaba-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "devlaba_db"
            - name: POSTGRES_USER
              value: "devlaba_user"
            - name: POSTGRES_PASSWORD
              value: "devlaba_password"
          volumeMounts:
            - name: devlaba-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: devlaba-storage
          persistentVolumeClaim:
            claimName: devlaba-pvc
